spring:
  application:
    name: cdc-orders

  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true